name: Lint

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up uv
        run: python -m pip install uv

      - name: Check style
        run: |
          python -m uv pip install pre-commit
          pre-commit run -a